### ISSUE TITLE
string GetConstructorName(this Type type) 확장 메서드 구현

### ISSUE THREAD

**Issue by gyuwon** [envicase/flip#13]
`InternalReflectionExtensions.GetConstructorName(Type)` 메서드는 아직 제대로 구현되지 않았습니다. 이 메서드가 구현되면 제네릭 형식에 대해서 C# 문법을 따르는 생성자 이름을 반환해야 합니다. 다음 예를 참고하세요.

| 형식 | 결과 |
| ---- | ---- |
| `Dictionary<Int32, String>` | Dictionary |
| `List<Nullable<Int32>>` | List |

**Comment by gongdo** [comment]
용법을 좀 더 명확히 할 필요가 있습니다.
constructor의 이름이 단순히 generic 정의를 포함하지 않는 타입명이라고 하면 이것은 constructor의 이름이라기보다는 단순한 타입 이름이라고 봐야겠습니다.

예를 들어 인터페이스 타입 ISomething<T>에 대한 GetConstructorName의 기대값은 어떤 것일까요?
- `ISomething` 이라면 단순한 타입이름을 원하는 것이고
- 그렇지 않다면 throw exception을 하는게 좋겠죠.

**Comment by gyuwon** [comment]
@gongdo 네 맞습니다. 인터페이스에 대해서는 예외가 던져지는 것이 옳겠습니다.

**Comment by gongdo** [comment]
@gyuwon 생성자가 없는 타입에 대해 예외를 던지는게 의도라면 GetConstructorName이라는 이름은 유지해도 될 것 같습니다. 굳이 더 자세히 표현하자면 GetPlainConstructorName이나 GetConstructablePlainTypeName 같이 길어지기만하고 별 도움은 안되는 형태가 될 것 같군요.

일단 네이밍은 유지하고 예외처리만 추가하도록 하죠.

**Comment by gyuwon** [comment]
@gongdo 넵.
