### ISSUE TITLE
Connection의 불필요한 finalizer 구현.

### ISSUE THREAD

**Issue by gongdo** [envicase/flip#5]
현재 `Connection`에는 unmanaged resource가 없습니다.
이 경우 finalizer (`~Connection()`)는 전혀 필요하지 않다고 알고 있는데요, 어떻게 생각하시는지요?

*참고: http://blog.stephencleary.com/2009/08/how-to-implement-idisposable-and.html

**Comment by gyuwon** [comment]
@gongdo 먹고살기 바쁘다보니 이제야 확인했네요. 맞는 지적이십니다. `Connection`에 Disposable 패턴은 적용할 필요가 없습니다.
